-- Datas passam a TIMESTAMPTZ: o valor deixa de depender do fuso da sessão do servidor.
-- Os valores existentes foram gravados pelo Prisma em UTC, então são lidos como UTC.

-- AlterTable
ALTER TABLE "Achievement" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "BackendInstance" ALTER COLUMN "startedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "startedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "heartbeatAt" SET DATA TYPE TIMESTAMPTZ(3) USING "heartbeatAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "BlockedUser" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "ContactSyncQuota" ALTER COLUMN "windowStart" SET DATA TYPE TIMESTAMPTZ(3) USING "windowStart" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "FriendRequest" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Friendship" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "FriendshipSuppression" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "GameAction" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "GameHand" ALTER COLUMN "startedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "startedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "endedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "endedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "GameTrick" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "IdempotencyKey" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ(3) USING "expiresAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "JobLock" ALTER COLUMN "acquiredAt" SET DATA TYPE TIMESTAMPTZ(3) USING "acquiredAt" AT TIME ZONE 'UTC',
ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ(3) USING "expiresAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "LeagueGroup" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "finalizedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "finalizedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "LeagueMembership" ALTER COLUMN "joinedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "joinedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "LeagueProgress" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "LeagueScore" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "LeagueSeason" ALTER COLUMN "startAt" SET DATA TYPE TIMESTAMPTZ(3) USING "startAt" AT TIME ZONE 'UTC',
ALTER COLUMN "endAt" SET DATA TYPE TIMESTAMPTZ(3) USING "endAt" AT TIME ZONE 'UTC',
ALTER COLUMN "finalizedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "finalizedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "preparedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "preparedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "LeagueWeekResult" ALTER COLUMN "processedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "processedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Match" ALTER COLUMN "turnStartedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "turnStartedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "turnDeadlineAt" SET DATA TYPE TIMESTAMPTZ(3) USING "turnDeadlineAt" AT TIME ZONE 'UTC',
ALTER COLUMN "nextTickAt" SET DATA TYPE TIMESTAMPTZ(3) USING "nextTickAt" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "finishedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "finishedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "MatchEvent" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "MatchParticipant" ALTER COLUMN "disconnectedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "disconnectedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "MatchResult" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "MatchSeries" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "MatchmakingTicket" ALTER COLUMN "joinedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "joinedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "MigrationRecord" ALTER COLUMN "migratedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "migratedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Notification" ALTER COLUMN "readAt" SET DATA TYPE TIMESTAMPTZ(3) USING "readAt" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "PlayerStatistics" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "RateLimitBucket" ALTER COLUMN "windowStart" SET DATA TYPE TIMESTAMPTZ(3) USING "windowStart" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Room" ALTER COLUMN "inviteExpiresAt" SET DATA TYPE TIMESTAMPTZ(3) USING "inviteExpiresAt" AT TIME ZONE 'UTC',
ALTER COLUMN "lateJoinUntil" SET DATA TYPE TIMESTAMPTZ(3) USING "lateJoinUntil" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "RoomInvite" ALTER COLUMN "invitedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "invitedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "respondedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "respondedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ(3) USING "expiresAt" AT TIME ZONE 'UTC',
ALTER COLUMN "dismissedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "dismissedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "pushSentAt" SET DATA TYPE TIMESTAMPTZ(3) USING "pushSentAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "RoomSeat" ALTER COLUMN "joinedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "joinedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "inviteTokenExpiresAt" SET DATA TYPE TIMESTAMPTZ(3) USING "inviteTokenExpiresAt" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "lastSeenAt" SET DATA TYPE TIMESTAMPTZ(3) USING "lastSeenAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "UserAchievement" ALTER COLUMN "unlockedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "unlockedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "UserDevice" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "UserPresence" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "UserProfile" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WebhookEvent" ALTER COLUMN "receivedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "receivedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "processedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "processedAt" AT TIME ZONE 'UTC';

